spring.application.name=demo-rest

# GraphiQL — интерактивная IDE для тестирования GraphQL-запросов.
# Доступна по адресу http://localhost:8080/graphiql после запуска приложения.
spring.graphql.graphiql.enabled=true
dgs.graphiql.enabled=true
dgs.graphiql.path=/dgs

# Путь к GraphQL-endpoint
spring.graphql.path=/graphql

# Включаем интроспекцию схемы (удобно при разработке, отключите в продакшене)
spring.graphql.schema.introspection.enabled=true

# Общий уровень
logging.level.root=INFO

# Spring автоконфигурация (ОЧЕНЬ важно)
logging.level.org.springframework.boot.autoconfigure=DEBUG

# GraphQL (Spring)
logging.level.org.springframework.graphql=DEBUG

# DGS
logging.level.com.netflix.graphql.dgs=DEBUG

# Web / MVC
logging.level.org.springframework.web=DEBUG

# Hibernate (если вдруг влияет)
logging.level.org.hibernate=INFO